inherit_gem:
  rubocop-shopify: rubocop.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Style/MethodCallWithArgsParentheses:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false