name: adventofcode

type: ruby

up:
  - ruby: '3.2.2'
  - bundler

commands:
  console:
    desc: Open console with the gem loaded
    run: bin/console
  build:
    desc: Build the gem using rake build
    run: bin/rake build
  test:
    desc: Run tests
    syntax:
      argument: file
      optional: args...
    run:  |
      ${RSPEC_TEST_RUNNER:-bundle exec rspec}
  style:
    desc: Run rubocop
    aliases: [rubocop, lint]
    run: bin/rubocop -A
